version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map container port to host
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=VE3
      - DB_USER=host
      - DB_PASSWORD=1234
      - JWT_SECRET=mysecret
      - PORT=3000
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3330:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=VE3
      - MYSQL_USER=host
      - MYSQL_PASSWORD=1234
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
